### ISSUE TITLE
[Bug] App Closes When Pressing The OCR Buton in infinite scroll mode

### ISSUE THREAD

**Issue by cademcniven** [Rattlehead15/tachiyomiOCR#1] opened 2021-01-17 00:47 UTC
## Device information
* Tachiyomi version: most recent release
* Android version: 10 QKQ1
* Device: Mi Note 10

## Steps to reproduce
1. Open chapter
2. Tap OCR button

### Expected behavior
 you will be prompted to select the region of the screen which contains the word you want to look for. Once the region is selected, long press the OCR rectangle to scan the word and look it up in the dictionary

### Actual behavior
The app closes

**Comment by Rattlehead15** [comment] 2021-01-17 01:05
Hi, I just tried it in my android 10 phone (Moto G9 plus) and couldn't reproduce the issue. I'll keep you posted if I manage to

**Comment by cademcniven** [comment] 2021-01-17 01:41
I fiddled with it some more and ended up figuring it out! Actually, the problem is caused by having the reader in infinite scroll mode. It worked fine after switching it to be individual pages

**Comment by Rattlehead15** [comment] 2021-01-17 01:47
Oh that's actually great! Should be an easy fix, I'll see what I can do

**Comment by Rattlehead15** [comment] 2021-01-17 02:46
Should be fixed in [v0.1.1](https://github.com/Rattlehead15/tachiyomiOCR/releases/tag/v0.1.1-ocr)

**Closed by Rattlehead15** 2021-01-17 02:46 UTC
Labels: bug
